### ISSUE TITLE
Feature/Create predictions with machine learning

### ISSUE THREAD

**Issue by Sirenoman** [CrAvila/Proyecto-ACA#5]
# Predicctions with Machine Learning

- [x] Create base file
- [x] Making imports
- [x] Accumulate data to investigate
- [x] Create neural networks
- [x] Group data and send for research
- [x] Generate estimates
- [x] Create function that makes predictions with neural networks
- [x] Add changes to branch

**Comment by CrAvila** [comment]
Changed NN to RF
